#!/usr/bin/env zsh

function c() {
  local bookmark_name="$1"
  local bookmark; bookmark=$(egrep "\|${bookmark_name}$" "$BOOKMARKS_FILE" 2>/dev/null)
  
  if [[ -z "$bookmark" ]] ; then
    echo "Invalid name, please provide a valid bookmark name. For example:"
    echo "  c foo"
    echo
    echo "To bookmark a folder, go to the folder then do this (naming the bookmark 'foo'):"
    echo "  mark foo"
    return 1
  else
    local dir="${bookmark%%|*}"
    cd ${dir//\~/$HOME}
  fi
}
