#!/usr/bin/env zsh

local bookmark_name=$1

if [[ -z $bookmark_name ]]; then
  bookmark_name="${PWD:t}"
fi

# Is root dir?
if [[ -z $bookmark_name ]]; then
  bookmark_name='/'
fi

if ! egrep -q "^$(print -nD $PWD)\|" "$BOOKMARKS_FILE"; then
  # Store the bookmark as folder|name
  echo "$(print -nD $PWD)|$bookmark_name" >> $BOOKMARKS_FILE
  echo "Bookmark '$bookmark_name' saved"

  return 0
fi

echo 'Bookmark already existed'
return 1
